import streamlit as st
st.page_link("Welcome_page.py", label="Home", icon="🏠")
st.subheader("Content Overview")
st.write("Below are some introductions to the main categories of content you will encounter in this website. Click on any one of them if it interests you, and it will bring you to the first topic in that section!")
st.divider()
st.write("Human Topic 1-Why do we need food?")
st.write("Food is essential for life. It provides the energy our bodies need to move, grow, and stay warm. It also supplies important nutrients that help us stay healthy and fight off illness. Without food, our bodies would not be able to function properly. In this topic, you’ll learn why food is important for survival and how it supports our everyday activities.")
st.page_link("Human_Topic1.py", label="Proceed", icon="🍕")
st.divider()
st.write("Human Topic 2-Healthy Habits")
st.write("Healthy habits are the choices we make every day that help our bodies and minds stay strong and happy. From eating balanced meals to getting enough sleep, staying active, and keeping clean, these small actions make a big difference in how we feel. In this topic, you'll explore simple but powerful habits that lead to a healthier lifestyle.")
st.page_link("Human_Topic2.py", label="Proceed", icon="🍓")
st.divider()
st.write("Human Topic 3-The Skeletal System")
st.write("Not available right now, writing in progress.")
st.page_link("Human_Topic3.py", label="Proceed",icon="😄")
st.divider()
st.write("Plants Topic 1-Different Kinds of Plants")
st.write("Plants come in many shapes and sizes — from tiny mosses to tall trees and colorful flowers. In this topic, you'll learn about the different types of plants and what makes each one unique. You’ll also discover how to identify plant types by looking at their leaves, stems, flowers, and roots. Get ready to explore the amazing world of plants around us!")
st.page_link("Plants_Topic1.py", label="Proceed", icon="🍀")
st.divider()
st.write("Plants Topic 2-Why are Plants Important?")
st.write("Plants do much more than just look pretty — they help keep our planet alive! Plants give us the oxygen we breathe, food to eat, and even materials to build with. They also provide homes for animals and help clean the air and water. In this topic, you’ll learn why plants are so important to people, animals, and the environment.")
st.page_link("Plants_Topic2.py", label="Proceed", icon="🌷")
st.divider()
st.write("Plants Topic 3-Parts and Structure of Plants")
st.write("Not available right now, writing in progress.")
st.page_link("Plants_Topic3.py", label="Proceed", icon="🪴")
st.divider()
st.write("Animals Topic 1-Knowing a Few Common Animals")
st.write("Animals are all around us — in the sky, in the water, on land, and even in our homes! In this topic, you’ll get to know a few common animals, learn their names, and explore where they live and what they do. Get ready to discover the amazing world of animals, one creature at a time!")
st.page_link("Animals_Topic1.py", label="Proceed", icon="🐕")
st.divider()
st.write("Animals Topic 2-Herbivores, Carnivores, and Omnivores")
st.write("Animals eat different kinds of food to stay alive and healthy. Some eat only plants, some eat only meat, and others eat both! In this topic, you’ll learn about herbivores, carnivores, and omnivores — what they eat, how they live, and how to tell them apart.")
st.page_link("Animals_Topic2.py", label="Proceed", icon="🐙")
st.divider()
st.write("Animals Topic 3-Introduction to Animal Groups")
st.write("Not available right now, writing in progress.")
st.page_link("Animals_Topic3.py", label="Proceed", icon="🐳")
st.divider()
st.write("Credit to Chat GPT for writing the summary of each website.")

