import streamlit as st
col1, col2 = st.columns(2)
with col1:
    st.page_link("Welcome_page.py", label="Home", icon="🏠")
with col2:
    st.page_link("Content.py", label="Overview", icon="⭐️")

st.subheader(":rainbow[Why are Plants Important?]")
st.divider()
st.write("Plants keep the soil together and prevents erosion. Erosion is the process in which the earthen materials are transported and worn away by natural forces. These natural forces often feature wind or water. Plants also provide us with the air we breathe, because it gives oxygen. Plants have a process called photosynthesis, in which they use sunlight and creates energy to sustain themselves. A byproduct in this process is the absorption and release of oxygen, which is essential since humans and animals all need oxygen, and plants is a massive source of oxygen for everyday life. Plants are also an essential part of the water cycle. It provides us with the food we eat, such as fruit, vegetables, etc. Some plants can even be used for medicine. Trees, which are common plants that we encounter in our lives, provide some shade during hot, summer days, and are important in preventing air pollution. As we all know, we need paper for learning, going to school, and everyday life. Many things that we use everyday such as paper and wooden table all come from plants. They are also a good source of oil, perfumes and spices, which can also be applied in our daily life. Plants provide fibers such as cotton and jute, etc.As we all know, climate change is one of the biggest challenges humans and earth face right now. Plants play a significant role in climate regulation, since they absorb carbon dioxide, they can absorb a lot of carbon dioxide from the atmosphere, which helps to reduce global warming and reduce the greenhouse effect.")
st.write("Besides their essential functions in preventing erosion, aiding the water cycle, and regulating climate, plants play a crucial role in preserving biodiversity. Forests, grasslands, wetlands, and various plant-dense ecosystems create homes for numerous species of animals, insects, fungi, and even additional plants. This biodiversity is essential for sustaining balanced and resilient ecosystems, which subsequently aid agriculture, clean water, and disease control. Plants likewise assist in cleansing the environment. Some species can take in contaminants from the soil and air, a method called phytoremediation. Certain plants have the ability to remove heavy metals or harmful substances from polluted soil, restoring the land for use. Likewise, houseplants can enhance indoor air quality by removing harmful toxins and boosting humidity levels, supporting respiratory health. Additionally, areas abundant with vegetation—such as parks, gardens, and city forests—are recognized for enhancing mental health. Studies indicate that being in green spaces can alleviate stress, improve mood, increase concentration, and potentially decrease the likelihood of depression. In urban areas, vegetation contributes to diminishing the urban heat island effect by providing shade and transpiration, thus enhancing the livability of these spaces. From an economic viewpoint, plants aid various sectors including agriculture, pharmaceuticals, textiles, cosmetics, and construction. Without vegetation, these sectors would fail, greatly impacting worldwide economies and livelihoods, particularly in rural areas that rely directly on plant-derived resources. Ultimately, plants hold cultural, spiritual, and aesthetic significance globally. Numerous customs, festivals, and ceremonies feature particular plants or blooms, representing life, beauty, renewal, and hope. Having plants around us can foster creativity, promote tranquility, and enhance our bond with nature. ")
st.divider()

st.write("Citations")
st.write("efsa. “The Role of Plants.” European Food Safety Authority, 2024, www.efsa.europa.eu/en/plh4l/role-plants.“Importance of Plants.” Adventures at Your Place, www.adventuresatyourplace.com.au/importance-of-plants/. Accessed 6 May 2025.“List Ten Uses of Plants.” Unacademy, unacademy.com/content/question-answer/biology/list-ten-uses-of-plants/. Accessed 6 May 2025.National Geographic. “Erosion.” National Geographic, 7 June 2022, education.nationalgeographic.org/resource/erosion/.")
st.write("ChatGPT")